Fix: using string for NC_VERSION (easier to remember)

diff --git a/gw b/gw
--- a/gw
+++ b/gw
@@ -169,10 +169,10 @@ BATTERY_NORMAL=0
 BATTERY_LOW=1
 BATTERY_VOLTAGE_LOW=12 # scale x 10 <= 1.2V is low
 
-NC_NMAP=0
-NC_OPENBSD=1
-NC_TOYBOX=2
-NC_BUSYBOX=3
+NC_NMAP="nmap"
+NC_OPENBSD="openbsd"
+NC_TOYBOX="toybox"
+NC_BUSYBOX="busybox"
 
 PORT_GW_TCP=45000
 PORT_WIFICONFIG_SERVER_TCP=49123 # method 1: in wifi configuration part 3 in spec.
@@ -3298,7 +3298,7 @@ sendPacketnc() { #$1 - command
 
     odcmdstr="od -A n -t u1 -w$MAX_16BIT_UINT"
 
-    if [ "$NC_VERSION" -eq $NC_OPENBSD ]; then
+    if [ "$NC_VERSION" = $NC_OPENBSD ]; then
 
         # -N shutdown(2) the network socket after EOF on the input / from man nc - otherwise nc hangs
         nccmdstr="\"$NC_CMD\" -4 -N -w 1 $ncUDPOpt $host $port" 
@@ -3309,14 +3309,14 @@ sendPacketnc() { #$1 - command
         
         cmdstr="printf %b \"$PACKET_TX_ESCAPE\" $txpipecmd | $nccmdstr $rxpipecmd | $odcmdstr"
 
-    elif [ "$NC_VERSION" -eq $NC_NMAP ]; then
+    elif [ "$NC_VERSION" = $NC_NMAP ]; then
 
         #sleep to disable immediate EOF and shutdown of ncat -> which leads to data not received from udp socket
        
         nccmdstr="\"$NC_CMD\" -4 -w 1  $ncUDPOpt $host $port"
         cmdstr="{ printf %b \"$PACKET_TX_ESCAPE\" $txpipecmd ; sleep $timeout_nc; } |  $nccmdstr $rxpipecmd | $odcmdstr"
 
-    elif [ "$NC_VERSION" -eq $NC_TOYBOX ]; then
+    elif [ "$NC_VERSION" = $NC_TOYBOX ]; then
 
         nccmdstr="$NC_CMD -4 $ncUDPOpt $host $port"
         
@@ -3326,7 +3326,7 @@ sendPacketnc() { #$1 - command
 
         cmdstr="printf %b \"$PACKET_TX_ESCAPE\" $txpipecmd | $nccmdstr $rxpipecmd | $odcmdstr"
 
-    elif [ "$NC_VERSION" -eq $NC_BUSYBOX ]; then
+    elif [ "$NC_VERSION" = $NC_BUSYBOX ]; then
 
         nccmdstr="$NC_CMD $host $port"
 
@@ -3415,7 +3415,7 @@ discovery_nc() { #$1 - subnet for udp scan
 
     case "$KSH_VERSION" in
         *Android*)
-            echo >&2 "Error: UDP scanning for devices not supported ( -u -l options ), nc version $NC_VERSION_STR"
+            echo >&2 "Error: UDP scanning for devices not supported ( -u -l options ), nc version $NC_VERSION"
             # udp -u -l option gives 1 error code and 'nc: listen' output
             return "$ERROR_NC_UDP_SCAN_UNAVAILABLE"
             ;;
@@ -3423,7 +3423,7 @@ discovery_nc() { #$1 - subnet for udp scan
 
     if [ -z "$1" ]; then # set up server on 59387 port
 
-        if [ "$NC_VERSION" -ne $NC_NMAP ]; then
+        if [ "$NC_VERSION" = $NC_NMAP ]; then
             scan_max_iterations=30
             SCAN_NC_TIMEOUT=0.1
         fi
@@ -3431,7 +3431,7 @@ discovery_nc() { #$1 - subnet for udp scan
         if scan_result=$(
             n=0
             while [ $n -lt $scan_max_iterations ]; do
-                if [ "$NC_VERSION" -eq $NC_NMAP ]; then
+                if [ "$NC_VERSION" = $NC_NMAP ]; then
                     $NC_CMD -4 -u -i $scan_nc_idle_timeout -l $PORT_CLIENT_UDP 2>/dev/null | od -A n -w64 -t x1
                 else
                     timeout $SCAN_NC_TIMEOUT "$NC_CMD" -4 -u -l $PORT_CLIENT_UDP 2>/dev/null | od -A n -w64 -t x1
@@ -3912,13 +3912,13 @@ initnc()
     if [ -n "$NC_VERSION" ]; then
         
         #specifying override path to nc executable is possible: NC_CMD='/path/nc' ./gw ...
-        if [ "$NC_VERSION" -eq $NC_NMAP ]; then
+        if [ "$NC_VERSION" = $NC_NMAP ]; then
             [ -z "$NC_CMD" ] && NC_CMD=$(which ncat)
-        elif [ "$NC_VERSION" -eq $NC_OPENBSD ]; then
+        elif [ "$NC_VERSION" = $NC_OPENBSD ]; then
             [ -z "$NC_CMD" ] && NC_CMD=$(which nc)
-        elif [ "$NC_VERSION" -eq $NC_BUSYBOX ]; then
+        elif [ "$NC_VERSION" = $NC_BUSYBOX ]; then
             [ -z "$NC_CMD" ] && NC_CMD="$(which busybox) nc"
-        elif [ "$NC_VERSION" -eq $NC_TOYBOX ]; then
+        elif [ "$NC_VERSION" = $NC_TOYBOX ]; then
             [ -z "$NC_CMD" ] && NC_CMD="$(which toybox) nc"
         else
             EXITCODE_INITNC=$ERROR_DEPENDENCY_NC
@@ -3935,7 +3935,7 @@ initnc()
             # ls -l $(readlink -f /usr/bin/nc)
             case "$(readlink -f "$NC_CMD" 2>&1)" in 
                 
-                */nc.openbsd) NC_VERSION=$NC_OPENBSD 
+                */nc.openbsd|*/netcat) NC_VERSION=$NC_OPENBSD #nc.openbsd Ubuntu/netcat Fedora
                         logErr $DEBUG_NC "$DEBUG_FUNC nc version openbsd"
                         ;;
                 
@@ -5670,16 +5670,16 @@ httpServer()
 
     [ "$DEBUG" -eq 1 ] && >&2 echo Listening on port "$1"
 
-    if [ $NC_VERSION -eq $NC_NMAP ]; then 
+    if [ $NC_VERSION = $NC_NMAP ]; then 
         http_message=$("$NC_CMD" -l -i 0.1 "$1" 2>/dev/null) # - idle timeout to exit early, not waiting for client to close/FIN
         EXITCODE_HTTPSERVER=$? 
         if [ "$EXITCODE_HTTPSERVER" -eq 2 ]; then
           EXITCODE_HTTPSERVER=0 # 2 exit from nc when idle timeout expires (Ncat: Idle timeout expired (100 ms). QUITTING.)
         fi
-    elif [ $NC_VERSION -eq $NC_OPENBSD ]; then
+    elif [ $NC_VERSION = $NC_OPENBSD ]; then
         http_message=$("$NC_CMD" -l -w 1 "$1" 2>/dev/null) # - -w to exit on idle for 1s
         EXITCODE_HTTPSERVER=$?
-    elif [ $NC_VERSION -eq $NC_TOYBOX ]; then 
+    elif [ $NC_VERSION = $NC_TOYBOX ]; then 
         http_message=$("$NC_CMD" -p "$1" -W 1 -l  2>/dev/null) # - -W to exit on idle for 1s
         EXITCODE_HTTPSERVER=$?
     else
@@ -6196,7 +6196,7 @@ while [ $# -gt 0 ]; do
             [ -n "$BASH_VERSION" ] && HTTP_UA="$HTTP_UA bash $BASH_VERSION"
             [ -n "$ZSH_VERSION" ] && HTTP_UA="$HTTP_UA zsh $ZSH_VERSION"
             [ -n "$KSH_VERSION" ] && HTTP_UA="$HTTP_UA ksh $KSH_VERSION"
-            HTTP_UA="$HTTP_UA nc $NC_VERSION_STR $(uname -srv)"
+            HTTP_UA="$HTTP_UA nc $NC_VERSION $(uname -srv)"
             HTTP_REQ_HOST="download.ecowitt.net"
             HTTP_REQ_PATH="/down/filewave?v=FirwaveReadme.txt"
             #HTTP_FIRMWARE_URL="http://$HTTP_REQ_HOST$HTTP_REQ_PATH"
