Fixed return of exitcode from sendpacketnc

diff --git a/gw b/gw
--- a/gw
+++ b/gw
@@ -50,6 +50,10 @@ ERROR_HTTP_MESSSAGE_EMPTY=10
 ERROR_NO_HOST_SPECIFIED=11
 ERROR_INVALID_SENSORID=12
 ERROR_INVALID_SENSORID_COMMAND=13
+ERROR_LISTEN_INVALID_PORTNUMBER=14
+ERROR_LISTEN_NOPORT=15
+ERROR_LISTEN_UNSUPPORTED_NC=16
+ERROR_COMMAND_UNKNOWN=17
 
 #to do: conversion
 UNIT_LIGHT="lux"
@@ -1358,10 +1362,10 @@ setTemperatureMode()
 {
     UNIT_TEMPERATURE_MODE=$1
     if [ "$UNIT_TEMPERATURE_MODE" -eq $UNIT_TEMPERATURE_CELCIUS ]; then 
-          UNIT_TEMP="C"
+          UNIT_TEMP="℃"
        
     elif [ "$UNIT_TEMPERATURE_MODE" -eq $UNIT_TEMPERATURE_FARENHEIT ]; then
-         UNIT_TEMP="F"
+         UNIT_TEMP="℉"
     fi
     
     [ "$DEBUG" -eq 1 ] && >&2 echo Unit temperature : $UNIT_TEMP
@@ -2316,7 +2320,7 @@ printSensorLine()
 
    # if [ "$2" -ne "$SENSORID_DISABLE" ] && [ "$2" -ne "$SENSORID_SEARCH" ]; then 
      # 1 battery unicode is field size 4 in printf format string. TEST printf  "🔋 1.3 V" | od -A n -t x1 | wc -w -> 10
-        APPEND_FORMAT=$APPEND_FORMAT"%2u %9x %3u %1u %4s %-17s $SGI_SENSOR%9s$sgi_normal %-10s %15s\n" #just use one printf call builtin/external -> builds up entire format and argument strings
+        APPEND_FORMAT=$APPEND_FORMAT"%6u %9x %3u %1u %4s %-17s $SGI_SENSOR%9s$sgi_normal %-10s %15s\n" #just use one printf call builtin/external -> builds up entire format and argument strings
         APPEND_ARGS=$APPEND_ARGS"\"$1\" \"$2\" \"$3\" \"$4\"  \"$SENSORNAME_WH\" \"$SENSORNAME_SHORT\" \"$sensorstate\" \"$SBATTERY_STATE\" \"$sensorsignal_unicode\" "
    # else
    #     APPEND_FORMAT=$APPEND_FORMAT"$SGI_SENSOR%2u %9s %3u %1u$SGI_NORMAL\n" 
@@ -2345,8 +2349,8 @@ parseSensorIdNew()
 
     resetAppendBuffer
     
-    APPEND_FORMAT="%2s %9s %3s %1s %-4s %-17s %-9s %-10s %s\n%s\n"
-    APPEND_ARGS="T ID B S Type Name State Battery Signal ───────────────────────────────────────────────────────────────────── "
+    APPEND_FORMAT="%6s %9s %3s %1s %-4s %-17s %-9s %-10s %s\n%s\n"
+    APPEND_ARGS="Sensor ID B S Type Name State Battery Signal ───────────────────────────────────────────────────────────────────────── "
 
     [ "$DEBUG" -eq  1 ] && >&2 echo "SPATTERNID $SPATTERNID"
     
@@ -2595,6 +2599,10 @@ convertBufferFromDecToOctalEscape() {
 
 sendPacket() {
     sendPacketnc "$@" # $@ each arg expands to a separate word
+    EXITCODE_SENDPACKET=$?
+    
+    [ "$EXITCODE_SENDPACKET" -ne 0 ] && [ "$DEBUG" -eq 1 ] && echo >&2 "Sendpacket failed with error code $EXITCODE_SENDPACKET"
+    return $EXITCODE_SENDPACKET
 }
 
 sendPacketnc() { #$1 - command
@@ -2671,8 +2679,8 @@ sendPacketnc() { #$1 - command
 
         #sleep to disable immediate EOF and shutdown of ncat -> which leads to data not received from udp socket
        
-        nccmdstr="$NC_CMD -4 $ncUDPOpt $host $port"
-        cmdstr="{ printf %b \"$PACKET_TX_ESCAPE\"; sleep $timeout_nc; } | $nccmdstr | $odcmdstr"
+        nccmdstr="$NC_CMD -4 -w 1 $ncUDPOpt $host $port"
+        cmdstr="{ printf %b \"$PACKET_TX_ESCAPE\"; sleep $timeout_nc; } |  $nccmdstr | $odcmdstr"
 
     elif [ "$NC_VERSION" -eq $NC_TOYBOX ]; then
 
@@ -2694,20 +2702,24 @@ sendPacketnc() { #$1 - command
             echo >&2 Busybox nc does not support UDP
         fi
     else
-        echo >&2 "Error nc not found in sendPacketnc $ERROR_NO_NC"
+        echo >&2 "Error nc version $NC_VERSION not supported sendPacketnc $ERROR_NO_NC"
+        return "$ERROR_NO_NC"
     fi
 
     if [ -n "$cmdstr" ]; then
        if [ -n "$OPTION_SHOW_COMMAND" ] && [ "$OPTION_SHOW_COMMAND" -eq 1 ]; then
          printf "%s\n" "$cmdstr"
        fi
-       od_buffer=$(eval "$cmdstr")
-        parsePacket "$od_buffer"
+       od_buffer=$(eval "$cmdstr" )
+       #maybe use: https://stackoverflow.com/questions/1550933/catching-error-codes-in-a-shell-pipe
+       parsePacket "$od_buffer"
+       EXITCODE_SENDPACKET=$?
     fi
 
     if [ -n "$KSH_VERSION" ]; then
        unset ncUDPOpt ncIdleOpt port host timeout_udp_broadcast useTimeout timeout_nc od_buffer cmdstr nccmdstr odcmdstr
     fi
+
 }
 
 discovery() {
@@ -2815,7 +2827,7 @@ checksum() {
 
     sum=0
 
-    [ "$DEBUG" -eq 1 ] && >&2 echo  "Running checksum on $1"
+    [ "$DEBUG" -eq 1 ] && >&2 echo  "checksum calculation on $1"
     
     IFS=" "
     for BYTE in $1; do
@@ -3506,6 +3518,7 @@ processCommand() {
                 #sendEcowittInterval "$1"
                 sendEcowittIntervalnew "$1"
             fi
+            
             ;;
 
         wunderground | wu)
@@ -3562,6 +3575,8 @@ processCommand() {
                   >&2 echo Cannot update customized, failed to read customized settings
                 fi
             fi
+            
+
             ;;
 
        # path | p) # deprecate?
@@ -3593,6 +3608,7 @@ processCommand() {
 
             if [ -z "$LOG_LIVEDATA" ]; then
                 sendPacket $CMD_LIVEDATA
+                EXITCODE_PROCESSCOMMAND=$EXITCODE_SENDPACKET
             else
               
                 while true; do
@@ -3611,9 +3627,10 @@ processCommand() {
         sensor_id_new | sid | sensor | s) # for new SENSOR_TYPE types
 
             if ! argEmptyOrOption "$1"; then
+             #filter for senorid; -c sensor connected|-c s c
               case "$1" in 
                 connected|c)
-                   SPATTERNID=1
+                   SPATTERNID=1 #matches connected sensors
                    sendPacket $CMD_READ_SENSOR_ID_NEW
                    ;;
                 searching|s)
@@ -3647,10 +3664,13 @@ processCommand() {
         *)
 
             echo >&2 Error Unknown command "$COMMAND" "$@"
-            return 1
+            return "$ERROR_COMMAND_UNKNOWN"
             ;;
     esac
-    return 0
+
+    EXITCODE_PROCESSCOMMAND=$EXITCODE_SENDPACKET
+
+    return $EXITCODE_PROCESSCOMMAND
 }
 
 isNumber() {
@@ -4360,9 +4380,11 @@ parseWundergroundHttpRequest()
 
 }
 
-httpServerEcowittWunderground()
+httpServer()
 #$1 - port number 
 {
+    EXITCODE_HTTPSERVER=0
+
     if [ "$SHELL_SUPPORT_TYPESET" -eq 1 ]; then
       #shellcheck disable=SC3044
       typeset http_message
@@ -4370,16 +4392,24 @@ httpServerEcowittWunderground()
       local http_message
     fi
 
-    [ "$DEBUG" -eq 1 ] && >&2 echo Listening on port "$1".
+    [ "$DEBUG" -eq 1 ] && >&2 echo Listening on port "$1"
 
     if [ $NC_VERSION -eq $NC_NMAP ]; then 
         http_message=$( nc -l -i 0.1 "$1" 2>/dev/null) # - idle timeout to exit early, not waiting for server to close/FIN
+        if [ $? -eq 2 ]; then
+          EXITCODE_HTTPSERVER=0 # 2 exit from nc when idle timeout expires (Ncat: Idle timeout expired (100 ms). QUITTING.)
+        else
+          EXITCODE_HTTPSERVER=$?
+        fi
     elif [ $NC_VERSION -eq $NC_OPENBSD ]; then
         http_message=$( nc -l -w 1 "$1" 2>/dev/null) # - -w to exit on idle for 1s
+        EXITCODE_HTTPSERVER=$?
     elif [ $NC_VERSION -eq $NC_TOYBOX ]; then 
         http_message=$( nc -p "$1" -W 1 -l  2>/dev/null) # - -W to exit on idle for 1s
+        EXITCODE_HTTPSERVER=$?
     else
-        echo >&2 Error unsupported nc version "$NC_VERSION"
+        echo >&2 Error unsupported listen for nc version "$NC_VERSION"
+        EXITCODE_HTTPSERVER=$ERROR_LISTEN_UNSUPPORTED_NC
     fi
 
     if [ -z "$http_message" ]; then
@@ -4387,8 +4417,12 @@ httpServerEcowittWunderground()
         return $ERROR_HTTP_MESSSAGE_EMPTY
     fi
 
-    if [ "$DEBUG" -eq 1 ] || [ -n "$OPTION_SHOW_HTTP_REQUEST" ] && [ "$OPTION_SHOW_HTTP_REQUEST" -eq 1  ] ; then
-        echo >&2 "$http_message"
+    if [ "$DEBUG" -eq 1 ]; then
+       if [ -n "$OPTION_SHOW_HTTP_REQUEST" ]; then
+         if  [ "$OPTION_SHOW_HTTP_REQUEST" -eq 1  ] ; then
+            echo >&2 "$http_message"
+         fi
+       fi
     fi
     
     case "$http_message" in
@@ -4406,6 +4440,8 @@ httpServerEcowittWunderground()
     if [ -n "$KSH_VERSION" ]; then
       unset http_message
     fi
+
+    return $EXITCODE_HTTPSERVER
 }
 
 cleanup()
@@ -4477,6 +4513,8 @@ initUnit
 #useful CLI info: https://clig.dev/#arguments-and-flags
 
 while [ $# -gt 0 ]; do
+
+    EXITCODE_MAIN=0
 
     KEY="$1"
 
@@ -4571,6 +4609,7 @@ while [ $# -gt 0 ]; do
             shift 1 # remove -c
 
             processCommand "$@"
+            EXITCODE_MAIN=$?
 
             for param in "$@"; do #remove params to command (until new - option)
 
@@ -4608,11 +4647,6 @@ while [ $# -gt 0 ]; do
 
         -g | --host)
 
-            #if ! connect "$2"; then
-            #  >&2 echo  "$HOST" "Error Failed to connect host $2, exiting"
-            #  disconnect
-            #  exit $ERROR_CONNECTION
-            #fi
             C_host="$2"
             #sendPacket "$CMD_READ_MAC" >/dev/null
             sendPacket "$CMD_READ_VERSION" >/dev/null
@@ -4638,23 +4672,30 @@ while [ $# -gt 0 ]; do
 
             if argEmptyOrOption "$2"; then
                 >&2 echo No port specified for listen
+                EXITCODE_MAIN=$ERROR_LISTEN_NOPORT
                 shift 
                 continue #process next option
             elif ! isNumber "$2"; then
                >&2 echo Not a valid port number
+               EXITCODE_MAIN=$ERROR_LISTEN_INVALID_PORTNUMBER
                shift; continue
             fi
 
             setUVMode $UNIT_UV_WATTM2
 
             if [ -z "$LOG_LIVEDATA" ]; then
-               httpServerEcowittWunderground "$2"
+               httpServer "$2"
+               EXITCODE_MAIN=$?
             else
                while true; do
-                  httpServerEcowittWunderground "$2"
+                  if ! httpServer "$2"; then
+                    EXITCODE_MAIN=$?
+                    break
+                  fi
                 done
             fi 
-        shift 2
+
+            shift 2
 
         ;;
 
@@ -4765,3 +4806,7 @@ done
 
 #typeset +f - list all function names/ksh93
 #set # list all variables
+
+[ "$DEBUG" -eq 1 ] && echo >&2 Exit code $EXITCODE_MAIN
+
+exit $EXITCODE_MAIN
