fix: glob sensor_*.= parsing

diff --git a/gw b/gw
--- a/gw
+++ b/gw
@@ -1555,41 +1555,66 @@ processCustomizedPathWundergroundLongOpt()
 }
 
 processSensorLongOpt()
-# $1 sensortype, $2 option (disable/search/hexid)
+# $1 sensortype, $2 maxsensortype, $3 option --sensor=disable|search|hexid
 # set EXITCODE_PROCESSSENSORLONGOPT
 {
     EXITCODE_PROCESSSENSORLONGOPT=0
+    echo >&2 "processSensorLongOpt $*"
     IFS='='
+    set -x
     local_sensortype=$1
+    local_sensortype_max=$2
     
     #shellcheck disable=SC2086
-    set -- $2
+    set -- $3
+    local_sensorname=${1#--}
+
+    unset local_glob
+    case "$1" in
+        *.) echo >&2 Glob "$1"
+            local_glob=1
+    esac
+    set +x
     
     if getSensorIdCommandForFW "$GW_VERSION_INT" && sendPacket $VALUE_CMD_READ_SENSORID "$GW_HOST"; then
 
         case "$2" in
 
-            disable|disconnect|false|off)  sendSensorId "$local_sensortype" "" $SENSORID_DISABLE "$GW_HOST"
+            disable|disbled|disconnect|false|f|off|n|N|no|NO)  sendSensorId "$local_sensortype" "$local_sensortype_max" $SENSORID_DISABLE "$GW_HOST"
                                            sendPacket $VALUE_CMD_READ_SENSORID "$GW_HOST" #reparse SENSOR_*
                                     ;;
 
-            search|connect|true|on)      sendSensorId "$local_sensortype" "" $SENSORID_SEARCH "$GW_HOST"
+            search|searching|connect|true|t|on|y|Y|yes|YES)      sendSensorId "$local_sensortype" "$local_sensortype_max" $SENSORID_SEARCH "$GW_HOST"
                                          sendPacket $VALUE_CMD_READ_SENSORID "$GW_HOST"
                                     ;;
 
                         *)        if isHex "$2" && [ ${#2} -le 8 ];  then
-                                        sendSensorId "$local_sensortype" "" $(( 0x$2 )) "$GW_HOST"
-                                         sendPacket $VALUE_CMD_READ_SENSORID "$GW_HOST"
+                                        local_writeSensorId=0
+                                        if [ $local_glob -eq 0 ]; then
+                                            local_writeSensorId=1
+                                        elif [ $local_glob -eq 1 ]; then
+                                            if [ "$2" = $SENSORID_DISABLE_HEXTEXT ] || [ "$2" = $SENSORID_SEARCH_HEXTEXT ]; then
+                                              local_writeSensorId=1
+                                            else
+                                                echo >&2 "Error: Cannot set glob $local_sensorname to same hexid '$2'"
+                                            fi
+                                        fi
+                                        
+                                        if [ $local_writeSensorId -eq 1 ]; then
+                                            sendSensorId "$local_sensortype" "$local_sensortype_max" $(( 0x$2 )) "$GW_HOST"
+                                            sendPacket $VALUE_CMD_READ_SENSORID "$GW_HOST"
+                                        fi
+                                        unset local_writeSensorId
                                   else
                                         echo >&2 "Error: Invalid sensor id '$2', use disable |false | off | disconnect,  search | true | on | connect, hexid"
                                        EXITCODE_PROCESSSENSORLONGOPT=$ERROR_INVALID_SENSORID_COMMAND
                                   fi
                                   ;;
-
         esac
-
     fi
-    unset local_sensortype
+
+    unset local_sensortype local_sensortype_max local_sensorname
+
     return "$EXITCODE_PROCESSSENSORLONGOPT"
 }
 
@@ -2283,81 +2308,121 @@ while [ $# -gt 0 ]; do
                                                 shift
                                                 ;;
 
-        --$BACKUPNAME_SENSOR_WH65=*)            processSensorLongOpt 0 "$1"
+        --$BACKUPNAME_SENSOR_WH65=*)            processSensorLongOpt 0 0 "$1"
                                                 shift
                                                 ;;
     
-        --$BACKUPNAME_SENSOR_WH68=*)            processSensorLongOpt 1 "$1"
+        --$BACKUPNAME_SENSOR_WH68=*)            processSensorLongOpt 1 1 "$1"
                                                 shift
                                                 ;;
     
-        --$BACKUPNAME_SENSOR_WH80=*)            processSensorLongOpt 2 "$1"
+        --$BACKUPNAME_SENSOR_WH80=*)            processSensorLongOpt 2 2 "$1"
                                                 shift
                                                 ;;
 
-        --$BACKUPNAME_SENSOR_RAINFALL=*)        processSensorLongOpt 3 "$1"
+        --$BACKUPNAME_SENSOR_RAINFALL=*)        processSensorLongOpt 3 3 "$1"
                                                 shift
                                                 ;;
         
-        --$BACKUPNAME_SENSOR_OUTTEMP=*)         processSensorLongOpt 5 "$1"
+        --$BACKUPNAME_SENSOR_OUTTEMP=*)         processSensorLongOpt 5 5 "$1"
                                                 shift
                                                 ;;
 
-        --$BACKUPNAME_SENSOR_TEMP?=*) 
-                                                local_ch=${1#--"$BACKUPNAME_SENSOR_TEMP"}
+         --"$BACKUPNAME_SENSOR_TEMP".=*)         local_type=6
+                                                processSensorLongOpt $local_type $((local_type + 7)) "$1"
+                                                unset local_ch local_type
+                                                shift
+                                                ;;
+
+        --$BACKUPNAME_SENSOR_TEMP?=*)           local_ch=${1#--"$BACKUPNAME_SENSOR_TEMP"}
                                                 local_ch=${local_ch%=*}
-                                                processSensorLongOpt $(( 5 + local_ch)) "$1"
-                                                unset local_ch
+                                                local_type=$(( 5 + local_ch))
+                                                processSensorLongOpt $local_type $local_type "$1"
+                                                unset local_ch local_type
+                                                shift
+                                                ;;
+
+        --"$BACKUPNAME_SENSOR_SOILMOISTURE".=*) local_type=14
+                                                processSensorLongOpt $local_type $((local_type + 7)) "$1"
+                                                unset local_ch local_type
                                                 shift
                                                 ;;
 
         --$BACKUPNAME_SENSOR_SOILMOISTURE?=*) 
                                                 local_ch=${1#--"$BACKUPNAME_SENSOR_SOILMOISTURE"}
                                                 local_ch=${local_ch%=*}
-                                                processSensorLongOpt $(( 13 + local_ch)) "$1"
-                                                unset local_ch
+                                                local_type=$(( 13 + local_ch))
+                                                processSensorLongOpt $local_type $local_type "$1"
+                                                unset local_ch local_type
+                                                shift
+                                                ;;
+
+        --"$BACKUPNAME_SENSOR_PM25".=*)         local_type=22
+                                                processSensorLongOpt $local_type $((local_type + 3)) "$1"
+                                                unset local_ch local_type
                                                 shift
                                                 ;;
 
         --$BACKUPNAME_SENSOR_PM25?=*) 
                                                 local_ch=${1#--"$BACKUPNAME_SENSOR_PM25"}
                                                 local_ch=${local_ch%=*}
-                                                processSensorLongOpt $(( 21 + local_ch)) "$1"
-                                                unset local_ch
+                                                local_type=$(( 21 + local_ch))
+                                                processSensorLongOpt $local_type $local_type "$1"
+                                                unset local_ch local_typoe
                                                 shift
                                                 ;;
    
-        --$BACKUPNAME_SENSOR_LIGHTNING=*)       processSensorLongOpt 26 "$1"
+        --$BACKUPNAME_SENSOR_LIGHTNING=*)       processSensorLongOpt 26 26 "$1"
+                                                shift
+                                                ;;
+        
+        --"$BACKUPNAME_SENSOR_LEAK".=*)         local_type=27
+                                                processSensorLongOpt $local_type $((local_type + 3)) "$1"
+                                                unset local_ch local_type
                                                 shift
                                                 ;;
 
         --$BACKUPNAME_SENSOR_LEAK?=*) 
                                                 local_ch=${1#--"$BACKUPNAME_SENSOR_LEAK"}
                                                 local_ch=${local_ch%=*}
-                                                processSensorLongOpt $(( 26 + local_ch)) "$1"
-                                                unset local_ch
+                                                local_type=$(( 26 + local_ch))
+                                                processSensorLongOpt $local_type $local_type "$1"
+                                                unset local_ch local_type
+                                                shift
+                                                ;;
+    
+         --"$BACKUPNAME_SENSOR_SOILTEMP".=*)    local_type=31
+                                                processSensorLongOpt $local_type $((local_type + 7)) "$1"
+                                                unset local_ch local_type
+                                                shift
+                                            ;;
+       
+        --$BACKUPNAME_SENSOR_SOILTEMP?=*)       local_ch=${1#--"$BACKUPNAME_SENSOR_SOILTEMP"}
+                                                local_ch=${local_ch%=*}
+                                                local_type=$(( 30 + local_ch))
+                                                processSensorLongOpt $local_type $local_type "$1"
+                                                unset local_ch local_type
+                                                shift
+                                                ;;
+
+        --$BACKUPNAME_SENSOR_CO2=*)             processSensorLongOpt 39 39 "$1"
+                                                shift
+                                                ;;
+        
+        --"$BACKUPNAME_SENSOR_LEAFWETNESS".=*)  local_type=40
+                                                processSensorLongOpt $local_type $((local_type + 7)) "$1"
+                                                unset local_ch local_type
+                                                shift
+                                            ;;
+
+        --$BACKUPNAME_SENSOR_LEAFWETNESS?=*)    local_ch=${1#--"$BACKUPNAME_SENSOR_LEAFWETNESS"}
+                                                local_ch=${local_ch%=*}
+                                                local_type=$(( 39 + local_ch))
+                                                processSensorLongOpt $local_type $local_type "$1"
+                                                unset local_ch local_type
                                                 shift
                                                 ;;
        
-        --$BACKUPNAME_SENSOR_SOILTEMP?=*) 
-                                                local_ch=${1#--"$BACKUPNAME_SENSOR_SOILTEMP"}
-                                                local_ch=${local_ch%=*}
-                                                processSensorLongOpt $(( 30 + local_ch)) "$1"
-                                                unset local_ch
-                                                shift
-                                                ;;
-
-        --$BACKUPNAME_SENSOR_CO2=*)             processSensorLongOpt 39 "$1"
-                                                shift
-                                                ;;
-        --$BACKUPNAME_SENSOR_LEAFWETNESS?=*) 
-                                                local_ch=${1#--"$BACKUPNAME_SENSOR_LEAFWETNESS"}
-                                                local_ch=${local_ch%=*}
-                                                processSensorLongOpt $(( 39 + local_ch)) "$1"
-                                                unset local_ch
-                                                shift
-                                                ;;
-
         --sensor)                               if  isGWdevice "$GW_VERSION" && getSensorIdCommandForFW "$GW_VERSION_INT"; then
                                                     sendPacket "$VALUE_CMD_READ_SENSORID" "$GW_HOST"
                                                     printSensors
